name = "honey-shop-api"
main = "src/index.ts"
compatibility_date = "2026-09-19"

[vars]
CORS_ORIGIN = "http://localhost:3000"
APP_URL = "http://localhost:3000"
RESEND_FROM = "Honey Shop <noreply@example.com>"

[[d1_databases]]
binding = "DB"
database_name = "honey-shop-db"
database_id = "6bb1de6b-5613-4b00-88dc-9e0792b3e77c"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "honey-shop-media"
