'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { ExternalLink, Search, UserRound, Wallet } from 'lucide-react';
import { AdminButton, AdminInput } from './AdminUI';

type Customer = { id: string; email: string; name: string; facebookUrl?: string | null; active: boolean; createdAt: string; points: number; rentalCount: number };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/v1${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) }, ...init }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Không thể hoàn tất thao tác.'); return data as T; }

export function CustomerManager() {
  const [items, setItems] = useState<Customer[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(''); const [adjustId, setAdjustId] = useState(''); const [editId, setEditId] = useState(''); const [editName, setEditName] = useState(''); const [editFacebook, setEditFacebook] = useState(''); const [delta, setDelta] = useState(''); const [reason, setReason] = useState('');
  async function load(q = query) { setLoading(true); try { setItems(await api<Customer[]>(`/admin/customers?q=${encodeURIComponent(q)}`)); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(''); }, []);
  async function toggle(customer: Customer) { setBusyId(customer.id); try { await api(`/admin/customers/${customer.id}`, { method: 'PATCH', body: JSON.stringify({ active: !customer.active }) }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusyId(''); } }
  async function saveProfile(event: FormEvent) { event.preventDefault(); setBusyId(editId); try { await api(`/admin/customers/${editId}`, { method: 'PATCH', body: JSON.stringify({ name: editName, facebookUrl: editFacebook }) }); setEditId(''); await load(); } catch (e) { setError((e as Error).message); } finally { setBusyId(''); } }
  async function adjust(event: FormEvent) { event.preventDefault(); setBusyId(adjustId); try { await api(`/admin/customers/${adjustId}/points`, { method: 'POST', body: JSON.stringify({ pointsDelta: Number(delta), note: reason }) }); setAdjustId(''); setDelta(''); setReason(''); await load(); } catch (e) { setError((e as Error).message); } finally { setBusyId(''); } }
  return <div className="space-y-4">
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <form onSubmit={e => { e.preventDefault(); void load(); }} className="admin-card flex flex-wrap gap-3 p-4"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400" /><AdminInput value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder="Tìm tên hoặc email khách" /></div><AdminButton>Tìm kiếm</AdminButton></form>
    {loading ? <div className="admin-card p-8 text-sm text-neutral-500">Đang tải tài khoản khách…</div> : items.length ? <div className="space-y-3">{items.map(customer => <article key={customer.id} className="admin-card p-4 sm:p-5"><div className="flex flex-wrap items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-800"><UserRound size={22} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-extrabold">{customer.name}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${customer.active ? 'bg-emerald-50 text-emerald-700' : 'bg-neutral-100 text-neutral-500'}`}>{customer.active ? 'Hoạt động' : 'Đã khóa'}</span></div><p className="mt-1 text-sm text-neutral-500">{customer.email}</p><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-neutral-500"><span className="inline-flex items-center gap-1.5 font-bold text-amber-800"><Wallet size={14} />{customer.points.toLocaleString('vi-VN')} điểm</span><span>{customer.rentalCount} đơn thuê</span><span>Tạo {new Date(customer.createdAt).toLocaleDateString('vi-VN')}</span>{customer.facebookUrl && <a href={customer.facebookUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-blue-700 underline">Facebook <ExternalLink size={12} /></a>}</div></div><div className="flex flex-wrap gap-2"><AdminButton type="button" variant="secondary" onClick={() => { setAdjustId(adjustId === customer.id ? '' : customer.id); setDelta(''); setReason(''); }}>Điều chỉnh điểm</AdminButton><AdminButton type="button" variant="secondary" onClick={() => { setEditId(editId === customer.id ? '' : customer.id); setEditName(customer.name); setEditFacebook(customer.facebookUrl || ''); }}>Sửa hồ sơ</AdminButton><AdminButton type="button" variant={customer.active ? 'danger' : 'secondary'} disabled={busyId === customer.id} onClick={() => void toggle(customer)}>{customer.active ? 'Khóa' : 'Mở khóa'}</AdminButton></div></div>
      {editId === customer.id && <form onSubmit={saveProfile} className="mt-4 grid gap-3 rounded-xl border border-neutral-200 bg-neutral-50 p-4 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Tên hiển thị<AdminInput required value={editName} onChange={e => setEditName(e.target.value)} /></label><label className="grid gap-1 text-xs font-bold">Link Facebook<AdminInput type="url" value={editFacebook} onChange={e => setEditFacebook(e.target.value)} placeholder="https://facebook.com/..." /></label><div className="sm:col-span-2"><AdminButton disabled={busyId === customer.id}>Lưu hồ sơ khách</AdminButton></div></form>}
      {adjustId === customer.id && <form onSubmit={adjust} className="mt-4 grid gap-3 rounded-xl border border-amber-200 bg-amber-50/60 p-4 sm:grid-cols-[180px_1fr_auto]"><AdminInput type="number" step="1" value={delta} onChange={e => setDelta(e.target.value)} placeholder="+ / − điểm" required /><AdminInput value={reason} onChange={e => setReason(e.target.value)} placeholder="Lý do điều chỉnh" required /><AdminButton disabled={busyId === customer.id}>Lưu điểm</AdminButton></form>}</article>)}</div> : <div className="admin-card p-10 text-center text-sm text-neutral-500">Chưa có tài khoản khách phù hợp.</div>}
  </div>;
}
