'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ExternalLink, EyeOff, MessageCircleHeart, Trash2 } from 'lucide-react';
import { AdminSelect } from './AdminUI';

type Feedback = { id: string; productTitle: string; productSlug: string; customerName: string; customerEmail?: string | null; content: string; imageUrl?: string | null; hideIdentity: boolean; status: 'PENDING' | 'APPROVED' | 'HIDDEN'; createdAt: string };
const statusLabel = { PENDING: 'Chờ duyệt', APPROVED: 'Đang hiển thị', HIDDEN: 'Đã ẩn' };
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`/api/v1${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) }, ...init }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Không thể hoàn tất thao tác.'); return data as T; }

export function FeedbackManager() {
  const [items, setItems] = useState<Feedback[]>([]); const [filter, setFilter] = useState('PENDING'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busyId, setBusyId] = useState('');
  async function load() { setLoading(true); try { setItems(await api<Feedback[]>(`/admin/feedback?status=${filter}`)); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [filter]);
  async function changeStatus(item: Feedback, status: string) { setBusyId(item.id); try { await api(`/admin/feedback/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusyId(''); } }
  async function remove(item: Feedback) { if (!confirm('Xóa feedback này?')) return; setBusyId(item.id); try { await api(`/admin/feedback/${item.id}`, { method: 'DELETE' }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusyId(''); } }
  return <div className="space-y-4">
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="admin-card flex flex-wrap items-center justify-between gap-3 p-4"><p className="text-sm text-neutral-500">Duyệt feedback trước khi hiển thị trên trang sản phẩm.</p><AdminSelect ariaLabel="Lọc feedback" value={filter} onChange={setFilter} searchable={false} allowEmpty={false} options={[{ value: 'PENDING', label: 'Chờ duyệt' }, { value: 'APPROVED', label: 'Đang hiển thị' }, { value: 'HIDDEN', label: 'Đã ẩn' }]} /></div>
    {loading ? <div className="admin-card p-8 text-sm text-neutral-500">Đang tải feedback…</div> : items.length ? <div className="grid gap-4 xl:grid-cols-2">{items.map(item => <article key={item.id} className="admin-card overflow-hidden"><div className="flex items-start justify-between gap-3 border-b border-neutral-100 p-4"><div className="min-w-0"><h2 className="truncate font-extrabold">{item.productTitle}</h2><p className="mt-1 text-xs text-neutral-500">{item.customerName}{item.hideIdentity && <span className="ml-2 inline-flex items-center gap-1 text-neutral-400"><EyeOff size={12} />Ẩn tên</span>}</p>{item.customerEmail && <p className="mt-1 text-xs text-neutral-400">{item.customerEmail}</p>}</div><Link href={`/cosplay/${item.productSlug}`} target="_blank" className="rounded-lg p-2 text-neutral-500 hover:bg-neutral-100" aria-label="Mở sản phẩm"><ExternalLink size={16} /></Link></div><div className="p-4"><p className="whitespace-pre-wrap text-sm leading-6 text-neutral-700">{item.content}</p>{item.imageUrl && <img src={item.imageUrl} alt="Ảnh khách gửi cùng feedback" className="mt-4 max-h-72 w-full rounded-xl border border-neutral-200 object-cover" />}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-neutral-100 pt-3"><span className="text-xs text-neutral-400">{new Date(item.createdAt).toLocaleString('vi-VN')}</span><div className="flex items-center gap-2"><AdminSelect ariaLabel={`Trạng thái feedback ${item.id}`} value={item.status} onChange={value => void changeStatus(item, value)} disabled={busyId === item.id} size="compact" searchable={false} allowEmpty={false} options={Object.entries(statusLabel).map(([value,label]) => ({ value, label }))} /><button type="button" disabled={busyId === item.id} onClick={() => void remove(item)} aria-label="Xóa feedback" className="rounded-lg p-2 text-neutral-400 hover:bg-red-50 hover:text-red-700 disabled:opacity-50"><Trash2 size={16} /></button></div></div></div></article>)}</div> : <div className="admin-card p-10 text-center"><MessageCircleHeart size={30} className="mx-auto text-neutral-300" /><p className="mt-3 font-bold">Không có feedback ở trạng thái này.</p></div>}
  </div>;
}
