import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const products = sqliteTable('products', {
  id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), description: text('description'),
  testPrice: integer('test_price').notNull().default(0), fesPrice: integer('fes_price').notNull().default(0), shootPrice: integer('shoot_price').notNull().default(0),
  thumbnailUrl: text('thumbnail_url'), status: text('status').notNull().default('AVAILABLE'), totalQuantity: integer('total_quantity').notNull().default(1),
  note: text('note'), location: text('location'), isCombo: integer('is_combo', { mode: 'boolean' }).notNull().default(false), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull()
});
export const productImages = sqliteTable('product_images', { id: text('id').primaryKey(), productId: text('product_id').notNull(), url: text('url').notNull(), alt: text('alt'), kind: text('kind').notNull().default('gallery') });
export const productVariants = sqliteTable('product_variants', { id: text('id').primaryKey(), productId: text('product_id').notNull(), name: text('name').notNull(), quantity: integer('quantity').notNull().default(0), attributes: text('attributes') });
export const posts = sqliteTable('posts', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), excerpt: text('excerpt'), content: text('content').notNull(), coverUrl: text('cover_url'), type: text('type').notNull().default('ARTICLE'), status: text('status').notNull().default('DRAFT'), seoTitle: text('seo_title'), seoDescription: text('seo_description'), publishedAt: text('published_at'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const rentals = sqliteTable('rentals', { id: text('id').primaryKey(), customerName: text('customer_name').notNull(), customerPhone: text('customer_phone'), startDate: text('start_date').notNull(), endDate: text('end_date').notNull(), status: text('status').notNull().default('HOLD'), deposit: integer('deposit').notNull().default(0), totalAmount: integer('total_amount').notNull().default(0), note: text('note'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const rentalItems = sqliteTable('rental_items', { id: text('id').primaryKey(), rentalId: text('rental_id').notNull(), productId: text('product_id').notNull(), variantId: text('variant_id'), quantity: integer('quantity').notNull().default(1), price: integer('price').notNull().default(0) });
export const users = sqliteTable('users', { id: text('id').primaryKey(), email: text('email').notNull().unique(), name: text('name').notNull(), role: text('role').notNull().default('STAFF'), passwordHash: text('password_hash').notNull(), passwordSalt: text('password_salt').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const sessions = sqliteTable('sessions', { id: text('id').primaryKey(), userId: text('user_id').notNull(), tokenHash: text('token_hash').notNull().unique(), expiresAt: text('expires_at').notNull(), createdAt: text('created_at').notNull() });
export const invitations = sqliteTable('invitations', { id: text('id').primaryKey(), email: text('email').notNull(), role: text('role').notNull().default('STAFF'), tokenHash: text('token_hash').notNull().unique(), expiresAt: text('expires_at').notNull(), acceptedAt: text('accepted_at'), createdBy: text('created_by').notNull(), createdAt: text('created_at').notNull() });
export const categories = sqliteTable('categories', { id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), parentId: text('parent_id'), imageUrl: text('image_url'), sortOrder: integer('sort_order').default(0), createdAt: text('created_at').notNull() });
export const tags = sqliteTable('tags', { id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), createdAt: text('created_at').notNull() });
export const productCategories = sqliteTable('product_categories', { productId: text('product_id').notNull(), categoryId: text('category_id').notNull() });
export const productTags = sqliteTable('product_tags', { productId: text('product_id').notNull(), tagId: text('tag_id').notNull() });
export const productComboItems = sqliteTable('product_combo_items', { comboProductId: text('combo_product_id').notNull(), itemProductId: text('item_product_id').notNull(), quantity: integer('quantity').notNull().default(1) });
