export const defaults = {
  windStrength: 0.42,
  windDirection: 0.65,
  windSpeed: 0.7,
  turbulence: 0.4,
  gustStrength: 0.5,
  hairAmplitude: 18,
  hairFrequency: 1.3,
  rootLock: 1,
  tipInfluence: 1,
  blinkEnabled: true,
  blinkFrequency: 1,
  breathingStrength: 0.7,
  breathingSpeed: 4.2,
  rainIntensity: 0.38,
  rainSpeed: 1,
  rainAngle: 0.08,
  rainOpacity: 0.28,
  foregroundAmount: 0.6,
  characterScale: 1,
  characterX: 0.12,
  characterY: 0,
  backgroundScale: 1.035,
  parallax: 0.45,
  mist: 0.15,
  idleStrength: 0.5,
  quality: "High",
  debug: "Off",
  bounds: false,
};
export type Settings = typeof defaults;
export const settings: Settings = { ...defaults };
